import { LayoutTransition } from '@/components/common/animation/LayoutTransition/LayoutTransition'
import Navbar from '@/components/Layout/Navbar/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="mx-auto h-full w-full max-w-screen-md flex-1 overflow-hidden">
      <LayoutTransition
        initial={{ opacity: 0, x: -50 }}
        animate={{ opacity: 1, x: 0, transition: { duration: 0.3 } }}
        exit={{ opacity: 0, x: 50, transition: { duration: 0.3 } }}
        className="h-full w-full"
      >
        <main className="flex flex-col h-full items-center justify-center">
          <Link href="/" className='block mb-5'>
            <button className="bg-black px-3 py-2 text-sm text-white rounded-md">
              Go Home
            </button>
          </Link>
          {children}
        </main>
      </LayoutTransition>
    </div>
  )
}
