import { LayoutTransition } from '@/components/common/animation/LayoutTransition/LayoutTransition'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="mx-auto h-full w-full max-w-screen-md flex-1 overflow-hidden">
      <LayoutTransition
        initial={{ opacity: 0, x: -50 }}
        animate={{ opacity: 1, x: 0, transition: { duration: 0.3 } }}
        exit={{ opacity: 0, x: 50, transition: { duration: 0.3 } }}
        className="h-full w-full"
      >
        <main className="h-full items-center justify-center flex">{children}</main>
      </LayoutTransition>
    </div>
  )
}
