import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import { UserProvider } from '@/contexts/UserContext/UserContext'
import ApolloProvider from '@/graphql/utils/ApolloProvider'
import { NextUIProvider } from '@nextui-org/react'
import { AnimatePresence } from 'framer-motion'
import { motion } from 'framer-motion'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex h-lvh flex-col bg-white text-black`}
      >
        <NextUIProvider>
          <ApolloProvider>
            <UserProvider>{children}</UserProvider>
          </ApolloProvider>
        </NextUIProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
