import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Layout/Navbar/Navbar";
import { UserProvider } from "@/contexts/UserContext/UserContext";
import ApolloProvider from "@/graphql/utils/ApolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-lvh bg-slate-900 text-white`}>
        <ApolloProvider>
          <UserProvider>
            <Navbar/>
            <div className="w-full max-w-screen-md flex-1 mx-auto">
              {children}
            </div>
          </UserProvider>
        </ApolloProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
